### PR TITLE
Adding unit cents and Midi controller for syntax highlighters

### PR DESCRIPTION
**Pull request by kmturley**
These will add additional annotations for syntax highlighters:
https://github.com/kmturley/sfz-syntax-highlighters

### CODE REVIEW

**Comment by DSmolken** [comment]
This is potentially a bit confusing as "MIDI Controller" or "loop" isn't really a unit. But I guess it makes sense to use the existing "unit" field for this because that's what the syntax highlighters will use?

Could also quibble with a few specific unit names for a few opcodes, but that's a minor thing we can sort out later.

**Comment by kmturley** [comment]
I took the language from the vscode extension here
https://github.com/jokela/vscode-sfz/blob/master/syntaxes/sfz.tmLanguage.json#L233

However some other options:
- midi values
- midi velocity

**Comment by DSmolken** [comment]
I see. Would being compatible with that vscode extension be valuable enough to users to keep the same nomenclature, or is it no biggie? I'm thinking just calling the MIDI-related opcodes as "Midi" for this purpose would be a little less confusing. But I don't think that's enough of a reason to break something that's already in use by many people.

**Comment by christophe-hall** [comment]
I'd be interested to know if editors other that vscode use the 'comment' field in textmate grammar files..?

I wonder if using 'cents' to describe units of percentage may be confusing versus its more common use to describe fractions of a semitone. In general 'cents' implies a relation to pitch or frequency.

**Comment by DSmolken** [comment]
I haven't forgotten about this, just been thinking... adding units that will be visible in the pages for things that are numbers without units could potentially confuse human readers.

There's gotta be a way to make both syntax highlighters and human readers of the page happy, but right now I don't know what that is. But we should definitely add cents as a unit to the pitch-based controls. Can we just do the cents for pitch opcodes as a first step (maybe another pull request), because that's clearly the right thing to do for those opcodes, and then leave the rest for later?

**Comment by christophe-hall** [comment]
> Would being compatible with that vscode extension be valuable enough to users to keep the same nomenclature, or is it no biggie?

I think Kim is referring to units mentioned in Arne's comments in the tmlanguage file. These don't form any part of the syntax rules and don't surface to users, so I think the answer is 'no biggie'.

**Comment by redtide** [comment]
I guess we can close this and check in a later moment a different solution, if Kim agrees, and based on [this comment](https://github.com/jokela/vscode-sfz/issues/5#issuecomment-1449402937) seems to be the case.

**Comment by kmturley** [comment]
@redtide is correct. As both syntax.yml and the syntax highlighter file are hand written, there are many differences. This means I have low confidence that these changes are actually correct.

I will close this PR!

Related to my comment, hand writing this file is slow and error prone. If I have time after sfz web player prototype, I will look into an alternative solution.

One possible approach would be to have a automated job, which installs each sfz player. Then runs each player with different input.sfz files. A different file to test each opcode. And compare the audio generated.
If the player output matches the test, then it passes and that opcode is tagged.

**Pull request closed without merging**
