### PR TITLE
Update software.yml

### PR DESCRIPTION
**Pull request by git-moss**
Added Bitwig Studio.

### CODE REVIEW

**Comment by redtide** [comment]
Hello, thank you for this, do we have by chance a list of opcodes supported by Bitwig?

**Comment by git-moss** [comment]
Thanks for the update! I heard back from Bitwig and these are the supported opcode:

alternate
default_path
end
group_label
hikey
hivel
key
lokey
loop_continuous
loop_crossfade
loop_end
loop_mode
loop_start
loop_sustain
loop_type
loopcrossfade
loopend
loopmode
loopstart
looptype
lovel
offset
pitch_keycenter
pitch_keytrack
region_label
sample
transpose
tune
volume
xfin_hikey
xfin_hivel
xfin_lokey
xfin_lovel
xfout_hikey
xfout_hivel
xfout_lovel

**Comment by redtide** [comment]
Thank you!

**Comment by bzeiss** [comment]
This is great. I went through the release notes of Bitwig for all major versions since version 3.3 (released 26 Nov 2020) up to 5.0.11, so that we have an update since the last post (only regarding the opcodes). The unmentioned versions up to 5.0.11 did not have any changes.

Bitwig 4.0 - Bitwig 4.0.8: 
- SFZ import: The seq_length opcode is now imported as Round-robin [26609]

Bitwig 4.1 - Bitwig 4.1.6:
- Any region using seq_position imports as Round-robin

**Pull request merged**
