### PR TITLE
Update define.md

### PR DESCRIPTION
**Pull request by jlearman**
See https://github.com/sfzformat/sfzformat.github.io/issues/34

### CODE REVIEW

**Comment by sagamusix** [comment]
I think it would make sense to put less blame on Sforzando here and describe it in a more general way. It should be listed as just one implementation (out of potentially several) doing it that way, and it should be spelled correctly. ;)

**Comment by jlearman** [comment]
Well, not sure how else to put it.  Not blaming so much as making clear what happens.  Oops about the typo, thanks for catching it!

**Comment by sagamusix** [comment]
I'd suggest something along the lines of

> Note, however, that it is not strictly defined how variables are propagated to #include files; Some implementations such as Sforzando just pass the last set value of the variable in the entire file to included files, while other implementations may actually use the last value as seen before the include statement.

I know the second sentence is terrible, maybe you can come up with a better formulation :)

**Comment by jlearman** [comment]
Fair enough!

**Comment by DSmolken** [comment]
I think we now have this better tested, and described correctly with the more recent pull request.

**Pull request closed without merging**
