### PR TITLE
Update syntax.yml

### PR DESCRIPTION
**Pull request by christophe-hall**
*_curveccN completions and corrections.

### CODE REVIEW

**Comment by DSmolken** [comment]
Do we use the a href syntax for other links, so we know it works? Or would we be trying it for the first time here?

**Comment by redtide** [comment]
> Do we use the a href syntax for other links, so we know it works? Or would we be trying it for the first time here?

Links in `short_description` are OK.

**Comment by DSmolken** [comment]
And this is the correct format for the links? In other words, do you think this is safe to merge, or should we test it on a local copy of the site first?

**Comment by redtide** [comment]
Looks OK to me, if I miss something I can fix it in this case.

**Pull request merged**
