### PR TITLE
Update syntax.yml

### PR DESCRIPTION
**Pull request by christophe-hall**
Extend negative territory to a few CC parameters.

### CODE REVIEW

**Comment by christophe-hall** [comment]
I guess a negative value for delay_cc might be wrong in terms of SFZv1 spec.

**Comment by DSmolken** [comment]
If there's delay in sfz1, it should be possible to apply a negative modulation value to that delay, shouldn't it? Or am I missing something?

**Comment by redtide** [comment]
I wonder why it was set to a 0/100 range if it would work also with negative values in.. rgc sfz plugin? ATM my Wine setup is dead so I can't test.

**Comment by DSmolken** [comment]
Should we leave this open until we can test, or merge it now and fix things later if we discover the negatives aren't supported?

**Comment by christophe-hall** [comment]
I will attempt to test

**Comment by redtide** [comment]
I think we should have documentation for both the original values and the "new" ones in the end, otherwise one can look at the opcode version and think that those values were the original for that version.

**Comment by christophe-hall** [comment]
Test shows that delay_cc may be negative with rgc's SFZ player. There are some interesting quirks with delay itself, but delay_cc1=-n nevertheless does what you'd expect.

**Pull request merged**
